In [1]:
import requests
import json
import pandas as pd
from dagster import asset,AutomationCondition
import geopandas as gpd
from datetime import datetime, date
import requests

In [5]:

base_url = "https://data.sfgov.org/resource/vi7r-brsi.csv"
count=0
limit=1000
count_query="$select=count(label)&$where=label='Measles, Indigenous' OR label='Measles, Imported'"

mpox_df=pd.read_csv(endpoint)
mpox_df=None
for i in range(0,count,limit):
    mpox_url = f"{base_url}&$offset={i}&$limit={limit}"

    try:
        this_df = gpd.read_file(mpox_url)
        if mpox_df is None:
            mpox_df = this_df
        else:
            mpox_df = pd.concat( [mpox_df, this_df],ignore_index=True)
    except Exception as e:
        print(e)

mpox_df

,episode_date,new_cases,cumulative_cases,max_episode_date,data_as_of,data_updated_at,data_loaded_at
0,2022-05-29T00:00:00.000,1,1,2025-06-25T00:00:00.000,2025-06-30T14:33:59.367,2025-06-30T09:00:03.393,2025-06-30T10:11:46.838
1,2022-05-30T00:00:00.000,1,2,2025-06-25T00:00:00.000,2025-06-30T14:33:59.367,2025-06-30T09:00:03.393,2025-06-30T10:11:46.838
2,2022-05-31T00:00:00.000,0,2,2025-06-25T00:00:00.000,2025-06-30T14:33:59.367,2025-06-30T09:00:03.393,2025-06-30T10:11:46.838
3,2022-06-01T00:00:00.000,1,3,2025-06-25T00:00:00.000,2025-06-30T14:33:59.367,2025-06-30T09:00:03.393,2025-06-30T10:11:46.838
4,2022-06-02T00:00:00.000,1,4,2025-06-25T00:00:00.000,2025-06-30T14:33:59.367,2025-06-30T09:00:03.393,2025-06-30T10:11:46.838
...,...,...,...,...,...,...,...
995,2025-02-17T00:00:00.000,0,968,2025-06-25T00:00:00.000,2025-06-30T14:33:59.367,2025-06-30T09:00:03.393,2025-06-30T10:11:46.838
996,2025-02-18T00:00:00.000,0,968,2025-06-25T00:00:00.000,2025-06-30T14:33:59.367,2025-06-30T09:00:03.393,2025-06-30T10:11:46.838
997,2025-02-19T00:00:00.000,0,968,2025-06-25T00:00:00.000,2025-06-30T14:33:59.367,2025-06-30T09:00:03.393,2025-06-30T10:11:46.838
998,2025-02-20T00:00:00.000,0,968,2025-06-25T00:00:00.000,2025-06-30T14:33:59.367,2025-06-30T09:00:03.393,2025-06-30T10:11:46.838
999,2025-02-21T00:00:00.000,0,968,2025-06-25T00:00:00.000,2025-06-30T14:33:59.367,2025-06-30T09:00:03.393,2025-06-30T10:11:46.838